<a href="https://colab.research.google.com/github/Abhishekkk2004/PyTorch-Basics/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [3]:
# using empty
## Assign memory of this shape and the values in there is assigned here
a = torch.empty(2,3)

In [4]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
# All zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
# b/w 0 and 1

torch.rand(2,3)

tensor([[0.6790, 0.4187, 0.7488],
        [0.2920, 0.0169, 0.6996]])

In [9]:
# use of seed
torch.rand(2,3)

tensor([[0.2407, 0.0335, 0.8351],
        [0.5240, 0.4648, 0.4736]])

In [10]:
# manual_seed
torch.manual_seed(100)
#With same seed, the random value remains sam4
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
b=torch.tensor([[1,2,3],[4,5,6]])

In [13]:
b.shape

torch.Size([2, 3])

In [14]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
# (SHAPE,WHICH ITEM)
print("using full ->", torch.full((3, 4), 5.5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5.5000, 5.5000, 5.5000, 5.5000],
        [5.5000, 5.5000, 5.5000, 5.5000],
        [5.5000, 5.5000, 5.5000, 5.5000]])


## Tensor Shapes

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])

## MAKING TENSOR OF SAME SHAPE AS X


In [17]:
torch.empty_like(x)

tensor([[      166637152, 137806888030128,               0],
        [              0,               0,               0]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [21]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
# find data type
x.dtype

torch.int64

In [23]:
# assign data type
c=torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

In [24]:
c

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
c.shape

torch.Size([3])

In [26]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [28]:
torch.manual_seed(100)
x = torch.rand(2,2)
x

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [29]:
# addition
## ALL OCCUR to all entries
x + 2
# subtraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0125, 0.6656],
        [0.0689, 0.2341]])

### 2. Element wise operation

In [30]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.6765, 0.7539, 0.2627],
        [0.0428, 0.2080, 0.1180]])
tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])


In [31]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0680, 0.0183, 0.2627],
        [0.0428, 0.2080, 0.1180]])

In [32]:
c = torch.tensor([1, -2, 3, -4])

In [33]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [34]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [35]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [36]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [37]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [38]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [39]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [40]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[1., 0., 4.],
        [3., 8., 7.]])

In [41]:
# sum
torch.sum(e)


tensor(23.)

In [42]:
# sum along columns
torch.sum(e, dim=0)

tensor([ 4.,  8., 11.])

In [43]:
# sum along rows
torch.sum(e, dim=-1)

tensor([ 5., 18.])

In [44]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([2.0000, 4.0000, 5.5000])

In [45]:
# median
torch.median(e)

tensor(3.)

In [46]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [47]:
# product
torch.prod(e)

tensor(0.)

In [48]:
# standard deviation
torch.std(e)

tensor(3.1885)

In [49]:
# variance
torch.var(e)

tensor(10.1667)

In [50]:
# argmax
torch.argmax(e)

tensor(4)

In [51]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [52]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[4, 6, 0],
        [1, 9, 9]])
tensor([[8, 0],
        [7, 0],
        [0, 9]])


In [53]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[74,  0],
        [71, 81]])

In [54]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [55]:
# transpose
torch.transpose(f, 0, 1)

tensor([[4, 1],
        [6, 9],
        [0, 9]])

In [56]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 7., 3.],
        [9., 4., 0.],
        [5., 7., 5.]])

In [57]:
# determinant
torch.det(h)

tensor(-86.0000)

In [58]:
# inverse
torch.inverse(h)

tensor([[-2.3256e-01,  1.6279e-01,  1.3953e-01],
        [ 5.2326e-01, -1.1628e-01, -3.1395e-01],
        [-5.0000e-01,  9.7031e-09,  5.0000e-01]])

### 5. Comparison operations

In [59]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 9, 7],
        [5, 9, 8]])
tensor([[9, 7, 9],
        [2, 6, 7]])


In [60]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[False,  True,  True],
        [ True,  True,  True]])

### 6. Special functions

In [61]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[7., 8., 3.],
        [6., 1., 5.]])

In [62]:
# log
torch.log(k)

tensor([[1.9459, 2.0794, 1.0986],
        [1.7918, 0.0000, 1.6094]])

In [63]:
# exp
torch.exp(k)

tensor([[1.0966e+03, 2.9810e+03, 2.0086e+01],
        [4.0343e+02, 2.7183e+00, 1.4841e+02]])

In [64]:
# sqrt
torch.sqrt(k)

tensor([[2.6458, 2.8284, 1.7321],
        [2.4495, 1.0000, 2.2361]])

In [65]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.9997, 0.9526],
        [0.9975, 0.7311, 0.9933]])

In [66]:
# softmax
torch.softmax(k, dim=0)

tensor([[7.3106e-01, 9.9909e-01, 1.1920e-01],
        [2.6894e-01, 9.1105e-04, 8.8080e-01]])

In [67]:
# relu
torch.relu(k)

tensor([[7., 8., 3.],
        [6., 1., 5.]])

## Inplace Operations

In [68]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6726, 0.5740, 0.9233],
        [0.9178, 0.7590, 0.7775]])
tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])


In [69]:
m.add_(n)

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [70]:
m

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [71]:
n

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])

In [72]:
torch.relu(m)

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [73]:
m.relu_()

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [74]:
m

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

## Copying a Tensor

In [75]:
a = torch.rand(2,3)
a

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [76]:
b = a # a and b occupy same memory location

In [77]:
b

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [78]:
a[0][0] = 0

In [79]:
a

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

B teo change hoye jacche

In [80]:
b

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [81]:
id(a)

137806888002256

In [82]:
id(b)

137806888002256

In [83]:
b = a.clone()

In [84]:
a

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [85]:
b

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [86]:
a[0][0] = 10

In [87]:
a

tensor([[10.0000,  0.3451,  0.0453],
        [ 0.9798,  0.5548,  0.6868]])

In [88]:
b

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [89]:
id(a)

137806888002256

In [90]:
id(b)

137806888041168

# Tensor operations on GPU

In [91]:
torch.cuda.is_available()

True

In [92]:
device=torch.device('cuda')

In [93]:
#Creating a new tensor on GPU
torch.manual_seed(100)
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [94]:
#moving normal tensor to GPU

In [95]:
torch.manual_seed(1100)
a=torch.rand(2,3)

In [96]:
a

tensor([[0.1455, 0.3973, 0.6823],
        [0.4747, 0.9475, 0.6063]])

In [97]:
b=a.to(device)

In [98]:
b

tensor([[0.1455, 0.3973, 0.6823],
        [0.4747, 0.9475, 0.6063]], device='cuda:0')

ADVANTAGE OF GPU


In [99]:
import time
# Define the size of the matrices
size = 10000 # Large size for performance comparison


# Create random matrices on CPU
matrix_cpu1 = torch. randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
Start_time = time. time ()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # Matrix multiplication on CPU
cpu_time = time.time() - Start_time
print(f"Time on CPU: {cpu_time: .4f} seconds")


# Move matrices to GPU
matrix_gpul = matrix_cpu1. to('cuda')
matrix_gpu2 = matrix_cpu2. to('cuda')


# Measure time on GPU
start_time = time. time()
result_gpu = torch.matmul(matrix_gpul, matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time = time. time() - start_time
print(f"Time on GPU: {gpu_time: .4f} seconds")
print(f"GPU speedup over CPU: X {cpu_time / gpu_time: .2f}")

Time on CPU:  18.7328 seconds
Time on GPU:  0.6465 seconds
GPU speedup over CPU: X  28.97
